<?php

$brands = [
    [
        'id'         => 1,
        'title'      => 'Voluptas deserunt',
    ],
    [
        'id'         => 2,
        'title'      => 'Et modi',
    ],
    [
        'id'         => 3,
        'title'      => 'Ut excepturi commodi',
    ],
    [
        'id'         => 4,
        'title'      => 'Sequi dolorum',
    ],
];

$categories = [
    [
        'id'         => 1,
        'title'      => 'A veniam nesciunt',
        'short_desc' => 'Voluptatem reiciendis placeat quis voluptatum saepe molestiae rerum culpa accusamus ea facilis molestias ea.',
        'long_desc'  => '<p>Porro illo officia rem in repudiandae at accusantium consequuntur. Consequatur hic autem mollitia itaque ratione. Sit nostrum aut rem eos perspiciatis sint. Suscipit molestias magni excepturi tempore.</p><p>Dolore dolorum non error debitis velit. Excepturi exercitationem ipsam possimus quis nihil laboriosam laudantium. Aspernatur id aut commodi perspiciatis.</p><p>A est praesentium perferendis ipsa vel repellat. Quis consequuntur veritatis iure ipsum. Distinctio est dolorem modi voluptas voluptas.</p><p>Ut veniam delectus neque illum laborum ad. Dolore quos ut quisquam quis blanditiis aut.</p>',
    ],
    [
        'id'         => 2,
        'title'      => 'Ea est',
        'short_desc' => 'Architecto voluptas sit aut dolor rerum enim laudantium nam tempore.',
        'long_desc'  => '<p>Deleniti eum veniam voluptas vel adipisci. Repudiandae consequuntur aut vel id delectus pariatur provident rem. Quae eveniet voluptate hic vel.</p><p>Et reiciendis sed fuga et et deleniti sapiente. Qui voluptas sapiente nostrum. Dolore magni culpa quia aut temporibus.</p><p>Impedit sit velit ex nihil voluptate voluptatem delectus. Et nihil possimus quam qui. Aut eos facilis eum rem. Sint perspiciatis ipsa aut soluta.</p>',
    ],
    [
        'id'         => 3,
        'title'      => 'Sunt minus',
        'short_desc' => 'Perspiciatis suscipit ea voluptatem sunt quia et numquam enim tempora voluptatem quam.',
        'long_desc'  => '<p>Et aut sequi officiis atque est. Sunt voluptates quos quia ratione. Sunt aut iure ex illo mollitia et qui. Sint exercitationem odit rerum exercitationem expedita id enim.</p><p>Illo dolorum doloribus dolore ut voluptas non dignissimos magnam. Praesentium ullam sed omnis quae repudiandae ducimus at. Autem eius nesciunt ducimus est quia.</p><p>Voluptas non omnis et quis repudiandae qui deserunt dolores. Culpa id veniam est reiciendis eos et. Blanditiis voluptas sit voluptatem neque officiis earum aut. Voluptatum ea voluptas sed dolorem velit optio.</p>',
    ],
    [
        'id'         => 4,
        'title'      => 'Blanditiis eius nemo',
        'short_desc' => 'Ad molestias ipsam possimus ut alias consequatur et illum impedit sint deserunt provident sed voluptas voluptatem maiores consequuntur esse sint sapiente aliquid.',
        'long_desc'  => '<p>Optio veniam id dolorem accusamus sit. Numquam possimus aliquid rerum facere earum optio nulla nihil. Amet odit vero amet aspernatur illum quia.</p><p>Autem molestias veritatis non quaerat inventore quis omnis. Ex consequatur sapiente quia facere omnis reprehenderit fugiat. Nulla aliquid vitae id ut ut et voluptatem.</p><p>Magni quae velit officiis. Esse sed dolor placeat quis nesciunt laborum. Quo quia eligendi ipsa ut facilis. Voluptas aspernatur laborum eos.</p>',
    ],
];

$products = [
    [
        'id'         => 1,
        'title'      => 'Eum magni facere qui iste',
        'category'   => 2,
        'brand'      => 4,
        'price'      => 376.56,
        'stock'      => 0,
        'short_desc' => 'Distinctio dolorem cupiditate enim culpa molestias et ut voluptas voluptatem qui est dolor perspiciatis.',
        'long_desc'  => '<p>Ullam et minima facilis quaerat fugit eum possimus. Dolorum libero assumenda earum nihil. Ex quo veniam sit reiciendis et excepturi.</p><p>Deserunt necessitatibus quia sequi neque quos. Aut voluptatibus iste quos impedit hic mollitia qui. Aut quidem nulla unde fuga asperiores.</p><p>Sunt nihil dolorem dolores reprehenderit voluptatem sed. Optio voluptate nulla et recusandae et est qui. Natus molestiae similique enim aut magnam.</p>',
        'releasedAt' => '2018-05-20',
    ],
    [
        'id'         => 2,
        'title'      => 'Deserunt error optio totam et',
        'category'   => 3,
        'brand'      => 1,
        'price'      => 688.88,
        'stock'      => 13,
        'short_desc' => 'Quidem dolorem aut iste qui aliquam et quae.',
        'long_desc'  => '<p>Recusandae impedit nihil illo fugit dolorem corporis. Labore in odit commodi cupiditate et. Nemo et commodi aut autem ut quod et. Odio magni doloremque quas. Qui ut consequatur quibusdam.</p><p>Animi eius eius repellendus est iusto. Ut vel aut eos et cum. Ea veniam quaerat et et repudiandae dolorem incidunt.</p><p>Qui occaecati sint nihil sint. Reiciendis id dolor aut voluptatem. Qui facere error autem.</p>',
        'releasedAt' => '2015-08-12',
    ],
    [
        'id'         => 3,
        'title'      => 'Quos illo est vel',
        'category'   => 4,
        'brand'      => 1,
        'price'      => 217.76,
        'stock'      => 0,
        'short_desc' => 'Earum ab illo dolor asperiores sapiente ad aut maiores vitae adipisci omnis aut nulla ducimus enim.',
        'long_desc'  => '<p>Beatae officiis dolore dolor quos incidunt. Quis totam quo eum voluptas nemo. Harum quae repudiandae accusantium dolorem. Odio vero a doloremque incidunt ab ipsum iure voluptatibus. Vero reprehenderit aut consequuntur optio ea voluptatem quia.</p><p>Ut id fugiat sequi dolore. Quia quo quae nihil atque ullam. Nostrum porro sed et natus. Est tempore quidem in esse iure labore ut nulla.</p><p>Repellat ipsam est ex pariatur dolore ratione quia. Repellendus autem nulla ut mollitia iusto ut. Quod deserunt laborum a labore repellat fugiat. Aut quaerat ut voluptas eaque. Accusantium vel molestiae alias error inventore et sit.</p>',
        'releasedAt' => '2018-06-06',
    ],
    [
        'id'         => 4,
        'title'      => 'Culpa error provident sunt optio',
        'category'   => 4,
        'brand'      => 1,
        'price'      => 869.93,
        'stock'      => 0,
        'short_desc' => 'Quam et vel est recusandae porro dolore quidem repellendus.',
        'long_desc'  => '<p>Blanditiis voluptatibus ducimus perspiciatis repellat quod mollitia. Beatae ipsa et ipsa molestias error incidunt. Atque et similique natus natus in officia praesentium.</p><p>Possimus nulla minus harum perferendis. Repellat consequuntur ratione aut qui voluptas delectus reiciendis. Architecto dignissimos qui laudantium culpa. Esse dolor mollitia aut officia amet voluptatem expedita.</p><p>Sit dolor praesentium veritatis quo repellat quia nulla et. Voluptatum ad dolor et eum quis. Laborum expedita quo qui unde ad rerum reiciendis.</p><p>Id qui quia consequatur doloribus optio molestias. Vel praesentium dolorem in maxime non repudiandae. Iure odit laudantium magnam vel et. Rerum nam odit quo id suscipit sequi sed.</p>',
        'releasedAt' => '2015-08-30',
    ],
    [
        'id'         => 5,
        'title'      => 'Voluptates adipisci voluptatem dolorem iure',
        'category'   => 1,
        'brand'      => 4,
        'price'      => 256.54,
        'stock'      => 0,
        'short_desc' => 'Autem culpa inventore ut aut culpa est natus quas ut animi.',
        'long_desc'  => '<p>Optio praesentium odio modi est et. Labore rerum ex eos dolore inventore. Debitis iste non sint corporis ex.</p><p>At aut dicta praesentium aspernatur totam. Aut in aut voluptatibus architecto molestiae dolores. Quidem quas dignissimos eius aliquid aliquid.</p><p>Id debitis possimus debitis reiciendis non. Ut ut dignissimos neque tempore vel velit voluptas. Et eaque rerum cumque qui et et.</p><p>Est ut necessitatibus voluptatibus optio placeat unde. Vel expedita saepe beatae aliquam. Repellendus fugit aliquid commodi autem ex. Et voluptatem et cupiditate id eum aut id.</p>',
        'releasedAt' => '2015-04-12',
    ],
    [
        'id'         => 6,
        'title'      => 'Doloribus necessitatibus impedit sit consequuntur',
        'category'   => 1,
        'brand'      => 4,
        'price'      => 394.93,
        'stock'      => 79,
        'short_desc' => 'Ut tenetur laudantium nemo qui occaecati incidunt modi fuga numquam non sunt.',
        'long_desc'  => '<p>Architecto quis necessitatibus repellendus eos. Ut laborum magnam nobis. Fuga placeat atque ut occaecati molestias.</p><p>Praesentium est velit rem. Nesciunt omnis commodi ullam consequuntur. Minus voluptatem impedit aut accusamus voluptas itaque sit. Amet velit sed consequatur libero et assumenda sit.</p><p>Repudiandae quas aut tempora dolores amet dolores dolores. Aut sit ipsa quisquam sint sint voluptate minima harum. Consequatur asperiores ut error corporis. Incidunt officiis numquam ullam et et.</p>',
        'releasedAt' => '2015-12-26',
    ],
    [
        'id'         => 7,
        'title'      => 'Officia eum sit reprehenderit neque',
        'category'   => 3,
        'brand'      => 2,
        'price'      => 875.28,
        'stock'      => 45,
        'short_desc' => 'Et qui omnis qui qui error debitis vitae voluptatem corporis et saepe amet nihil.',
        'long_desc'  => '<p>Sed fugiat vel magnam similique et corrupti et. Delectus dolorum voluptas nulla aut exercitationem. Nemo voluptatibus incidunt qui voluptas. Maiores dicta ullam ea omnis. Corporis inventore minima repellendus nulla rerum eius.</p><p>Maiores in ut est eos odit rerum. Dolores nihil delectus voluptates alias nulla doloremque numquam aut. Magnam est aut quas nihil quos ipsa.</p><p>Voluptatem fugit sint dolorem voluptatem et occaecati asperiores. Voluptate culpa vitae est vel ipsam nisi sed. Facere ut ut distinctio.</p>',
        'releasedAt' => '2017-08-09',
    ],
    [
        'id'         => 8,
        'title'      => 'Vel et ea nisi',
        'category'   => 2,
        'brand'      => 1,
        'price'      => 776.16,
        'stock'      => 0,
        'short_desc' => 'Unde nesciunt odit et sed a aut explicabo repellendus omnis corporis culpa dignissimos numquam natus error omnis quis illum aperiam eum aspernatur aut architecto.',
        'long_desc'  => '<p>Aut sed deserunt qui rerum. Nobis vel vero et laudantium beatae. Consequatur id id qui labore quo.</p><p>Minus et et autem repellendus maxime et. Rerum voluptas quia maxime amet qui hic saepe. Consequuntur quos eos accusamus quas rerum.</p><p>Odio porro dolor sed architecto sed impedit. Sed autem qui natus et et nam. Est aut reiciendis enim non sint nihil error.</p><p>Quis repellat ipsa modi tempore quos aspernatur. Et est quae odit eos pariatur placeat animi praesentium. In explicabo ab vel quis voluptas. Est aspernatur tempore molestiae et. Assumenda est exercitationem quia molestias.</p>',
        'releasedAt' => '2016-03-15',
    ],
    [
        'id'         => 9,
        'title'      => 'Aperiam qui porro suscipit',
        'category'   => 3,
        'brand'      => 1,
        'price'      => 966.12,
        'stock'      => 0,
        'short_desc' => 'Voluptatum non voluptatem et ullam ut impedit sequi enim.',
        'long_desc'  => '<p>Est eos eius adipisci maiores. Aut voluptatum officia expedita sunt dolorem. Consequatur quidem quam deleniti. Qui magni adipisci ullam occaecati natus.</p><p>Non minus quo iure sapiente qui delectus est. Dignissimos sit aliquid quia non est. Ad enim quis laboriosam omnis aut officiis. Fugit saepe optio ut quam laudantium voluptatem et libero.</p><p>Dignissimos odit consectetur esse sint optio accusantium dolorum. Sint iste voluptas molestiae ea atque cupiditate. Et aut soluta dolorem sed officiis. Mollitia provident sed minus veniam blanditiis eum aut.</p><p>Sed unde aperiam quaerat animi. Quis sed voluptate iste non. Maiores quo exercitationem delectus in quia voluptatem ex. Quia nobis sed sit et facere aut.</p>',
        'releasedAt' => '2019-02-11',
    ],
    [
        'id'         => 10,
        'title'      => 'Ea qui non voluptate',
        'category'   => 2,
        'brand'      => 4,
        'price'      => 280.48,
        'stock'      => 0,
        'short_desc' => 'Non ex a vitae et expedita aut inventore sed sunt aut eveniet ut in expedita repudiandae sunt magni dolorem iusto.',
        'long_desc'  => '<p>Temporibus et est aut quam qui. Aut quis impedit accusamus sunt voluptates. Id voluptatum sint amet consequuntur labore et.</p><p>Molestiae cum provident velit est. Ratione commodi id sapiente est dignissimos inventore expedita officiis. Ut et totam rem.</p><p>Quia quam accusantium repellat praesentium doloribus temporibus molestiae officiis. Possimus repellendus blanditiis omnis at. Quod eos est itaque suscipit nostrum. Aliquam quaerat quia iste in. Consequuntur quo labore ea et aut quia sit.</p>',
        'releasedAt' => '2019-02-10',
    ],
    [
        'id'         => 11,
        'title'      => 'Aspernatur iusto cum deserunt corrupti',
        'category'   => 1,
        'brand'      => 4,
        'price'      => 258.68,
        'stock'      => 34,
        'short_desc' => 'Voluptatum voluptatem delectus incidunt magni consequuntur aut voluptates repellendus ex laudantium non quia expedita ipsum ipsa.',
        'long_desc'  => '<p>Sit deserunt ut nulla aut. Et sint impedit impedit suscipit minus. Et sunt sed est itaque amet.</p><p>Quis labore et et quo accusantium et. Corrupti excepturi rerum corporis totam. Voluptatum consequatur fuga corrupti. In nemo laboriosam assumenda.</p><p>In enim dignissimos praesentium libero. Placeat hic libero consequatur est assumenda quisquam minima. Velit culpa maxime sunt in veniam voluptatem deleniti. Ipsum corporis est corporis molestias sed rerum.</p>',
        'releasedAt' => '2015-07-13',
    ],
    [
        'id'         => 12,
        'title'      => 'Aliquid eum sit temporibus',
        'category'   => 1,
        'brand'      => 2,
        'price'      => 185.25,
        'stock'      => 0,
        'short_desc' => 'Ut odio a cumque earum est occaecati dolore maxime aperiam consequatur quo et occaecati praesentium quidem.',
        'long_desc'  => '<p>Incidunt rem eum doloribus aut eum quas ab. Fugit voluptas quia rem accusantium enim repudiandae. Eius est officiis consequatur maxime soluta ex. Voluptas odit ab dolore.</p><p>Est odit qui vitae omnis ad ex excepturi. Rerum amet nihil quia in tempora. Est repellendus est quia quos in maiores blanditiis. Doloremque molestiae dolores est dolor aut quas facilis. Cum vero delectus temporibus.</p><p>Animi rerum eveniet rerum illum. Perferendis consectetur qui aliquam aliquid eaque laudantium. Sed esse et voluptates enim odit ullam.</p><p>Ipsum dolorum sint minima deleniti quam corrupti vero explicabo. Expedita corrupti esse repellendus minima vero accusamus cum dolorum. Dolor autem delectus temporibus officiis et quia quis vero.</p>',
        'releasedAt' => '2017-02-25',
    ],
    [
        'id'         => 13,
        'title'      => 'In sequi deleniti unde eum',
        'category'   => 2,
        'brand'      => 2,
        'price'      => 488.97,
        'stock'      => 10,
        'short_desc' => 'Doloremque quo culpa quidem quam sequi delectus voluptatibus occaecati in culpa consequatur perspiciatis necessitatibus et voluptatem odio.',
        'long_desc'  => '<p>At qui velit molestiae itaque quibusdam. Tempore ducimus alias rerum pariatur. Corrupti hic qui harum sint illum quae. Et qui ipsum voluptas dolore repellat consectetur et iure.</p><p>Voluptate sed est corporis praesentium quia ad. Possimus dolorem itaque voluptate beatae non quia. Magni deserunt et velit praesentium cum itaque non. Doloribus quia consequatur aut quia.</p><p>Repellendus qui repellat ipsa assumenda accusantium quasi aut. Aut vitae error ut eveniet rerum nihil voluptatum. Amet officiis amet aliquam et.</p><p>Ullam ea omnis est. Asperiores voluptas voluptatem a consectetur. Ut quod saepe officia. Eveniet ut molestias aut accusantium et.</p>',
        'releasedAt' => '2016-01-27',
    ],
    [
        'id'         => 14,
        'title'      => 'Est incidunt placeat ut quisquam',
        'category'   => 1,
        'brand'      => 3,
        'price'      => 346.53,
        'stock'      => 80,
        'short_desc' => 'Necessitatibus aut commodi dolor vel vitae qui quo soluta et sit laborum quas est esse enim.',
        'long_desc'  => '<p>Distinctio qui eos est harum cum molestiae debitis. Occaecati dolores tempora dolor sed. Nam sapiente voluptatem corrupti ad minus earum quis ut. Quas rerum ipsa in.</p><p>Dolorum est possimus occaecati velit. Rerum qui et est maxime ad provident omnis autem. Et autem et voluptatum eveniet consequatur enim placeat.</p><p>Cupiditate distinctio aliquam voluptas enim asperiores. Reprehenderit nostrum ab eaque omnis. Officiis vel cumque voluptatum. Qui atque modi omnis hic ut eum. Ut debitis eius quia fugit quis incidunt.</p>',
        'releasedAt' => '2018-05-20',
    ],
    [
        'id'         => 15,
        'title'      => 'Laboriosam expedita eum perferendis fugit',
        'category'   => 2,
        'brand'      => 3,
        'price'      => 122.28,
        'stock'      => 0,
        'short_desc' => 'Incidunt numquam sit possimus voluptate tempore nostrum nemo quo et voluptatem ullam amet itaque nostrum sint id dolorum optio.',
        'long_desc'  => '<p>Non vel sint autem modi impedit. Aut itaque aut voluptas impedit nemo assumenda tenetur incidunt. Repellendus natus autem tempora voluptatem similique. Molestiae saepe nulla quo neque alias enim aut.</p><p>Unde non voluptatem sint at magnam. Culpa occaecati quo dolores similique. Id autem rerum reprehenderit non et ea. Sint molestiae esse laborum quam.</p><p>Veniam eligendi ab ut labore. Sit ut laborum illum minus. Excepturi praesentium sint ut est.</p>',
        'releasedAt' => '2015-06-22',
    ],
    [
        'id'         => 16,
        'title'      => 'Ullam et vero optio',
        'category'   => 1,
        'brand'      => 3,
        'price'      => 52.15,
        'stock'      => 0,
        'short_desc' => 'Beatae sapiente dignissimos animi repudiandae sed modi sed et possimus ut rerum quam blanditiis velit dolor dolorum.',
        'long_desc'  => '<p>Repudiandae sequi at delectus qui alias ut. Est repellendus illo id et sit quis eum. Doloribus voluptate reiciendis sunt voluptate magnam.</p><p>Vel qui dicta et. Sed quis ipsum beatae doloribus laboriosam. Perferendis rerum placeat officiis nobis doloribus assumenda placeat. Animi aliquid voluptas minus provident sed impedit aspernatur. Velit nostrum vitae at dolore est.</p><p>Nam nesciunt quaerat eligendi eius perspiciatis fuga. Dolores veritatis ut natus voluptatibus ut non. Fugit voluptates aliquam repellendus unde amet dolores. Voluptates voluptatum non laudantium aut.</p>',
        'releasedAt' => '2015-10-04',
    ],
];
